Air Law
Meteorology
General Navigation
Radio Navigation
Operational Procedures
Principles of Flight
Instrumentation
Airframe, Systems, Electrics, Power Plant
Mass & Balance
Performance
Flight Planning & Monitoring
Knowledge, Skills and Attitudes (KSA)
Human Performance & Limitations
Communications
